version: '3'
services:
  bot:
    build: .
    restart: always  # Перезапускать контейнер всегда, если он падает
    volumes:
      - ./data:/app/data  # Монтирование директории для сохранения данных
